// ---------------------------------------------------------------------------
// Primitive Map – Data
// ---------------------------------------------------------------------------

const LAYERS = [
  {
    layer: "Foundation",
    label: "L1 \u2014 Foundation",
    subtitle: "Who",
    primitives: [
      {
        name: "Identity",
        pillars: ["Language", "Coordination"],
        formationRate: "~3%",
        tamUnlocked: "$30B+",
        maturity: "Emerging",
        definition: "Verifiable self in digital space",
        legacyEquivalent: "Usernames, emails, phone numbers, government ID",
        instantiations: [
          { name: "ENS" },
          { name: "Worldcoin" },
          { name: "SpruceID/DID" },
          { name: "Farcaster ID" },
          { name: "Lens Protocol" },
        ],
        composesWith: ["Credential", "Consent", "Reputation", "Agent"],
      },
      {
        name: "Credential / Claim",
        pillars: ["Language", "Coordination"],
        formationRate: "<1%",
        tamUnlocked: "$15B+",
        maturity: "Experimental",
        definition: "Provable attribute attached to identity",
        legacyEquivalent: "Diplomas, certificates, licenses, resumes",
        instantiations: [
          { name: "EAS" },
          { name: "Veramo" },
          { name: "Disco.xyz" },
          { name: "Ceramic" },
          { name: "Hypercerts" },
        ],
        composesWith: [
          "Identity",
          "Attestation",
          "Reputation",
          "Intent",
          "Agreement",
        ],
      },
      {
        name: "Attestation",
        pillars: ["Language", "Coordination"],
        formationRate: "<1%",
        tamUnlocked: "$10B+",
        maturity: "Experimental",
        definition: "Third-party verification of a claim",
        legacyEquivalent: "Notarization, background checks, audits",
        instantiations: [
          { name: "EAS" },
          { name: "Sign Protocol" },
          { name: "Clique" },
          { name: "Gitcoin Passport" },
          { name: "Verax" },
        ],
        composesWith: ["Credential", "Identity", "Reputation", "Credibility"],
      },
      {
        name: "Consent",
        pillars: ["Language", "Coordination"],
        formationRate: "<1%",
        tamUnlocked: "$5B+",
        maturity: "Experimental",
        definition: "Permission boundary for interaction",
        legacyEquivalent:
          "Terms of service, opt-ins, cookie banners, GDPR consent forms",
        instantiations: [
          { name: "XMTP", approach: "messaging consent" },
          { name: "Lit Protocol" },
          { name: "Index" },
          { name: "Sign Protocol" },
        ],
        composesWith: [
          "Identity",
          "Appropriateness",
          "Conversation",
          "Opportunity",
          "Agreement",
        ],
      },
    ],
  },
  {
    layer: "Context",
    label: "L2 \u2014 Context",
    subtitle: "What You Know",
    primitives: [
      {
        name: "Memory",
        pillars: ["Language"],
        formationRate: "~2%",
        tamUnlocked: "$80B+",
        maturity: "Emerging",
        definition: "Persistent context across interactions",
        legacyEquivalent:
          "CRM records, browsing history, note-taking, customer data platforms",
        instantiations: [
          { name: "Mem0" },
          { name: "Ceramic" },
          { name: "Index", approach: "agent memory" },
          { name: "LangMem" },
          { name: "Recall.ai" },
        ],
        composesWith: ["Knowledge", "Preference", "Intent", "Agent"],
      },
      {
        name: "Knowledge",
        pillars: ["Language"],
        formationRate: "~5%",
        tamUnlocked: "$25B+",
        maturity: "Emerging",
        definition: "Shared information layer",
        legacyEquivalent: "Wikis, databases, documentation, encyclopedias",
        instantiations: [
          { name: "The Graph" },
          { name: "Ceramic" },
          { name: "IPFS/Filecoin" },
          { name: "Dune Analytics" },
          { name: "Golden" },
        ],
        composesWith: ["Memory", "Oracle", "Proof"],
      },
      {
        name: "Preference",
        pillars: ["Language"],
        formationRate: "<1%",
        tamUnlocked: "$40B+",
        maturity: "Experimental",
        definition: "Declared or inferred user desires",
        legacyEquivalent:
          "User profiles, settings, cookies, recommendation engines",
        instantiations: [
          { name: "Index" },
          { name: "Ceramic" },
          { name: "Lens" },
          { name: "Farcaster" },
        ],
        composesWith: ["Intent", "Memory", "Appropriateness", "Opportunity"],
      },
      {
        name: "Appropriateness",
        pillars: ["Language"],
        formationRate: "<1%",
        tamUnlocked: "$15B+",
        maturity: "Theoretical",
        definition: "Privacy norms governing information flow",
        legacyEquivalent:
          "Social norms, privacy policies, data protection regulations",
        instantiations: [
          { name: "Index", approach: "contextual integrity" },
          { name: "Lit Protocol" },
          { name: "Oasis Network" },
          { name: "Nym" },
        ],
        composesWith: ["Consent", "Preference", "Opportunity", "Perception"],
      },
    ],
  },
  {
    layer: "Intent",
    label: "L3 \u2014 Intent",
    subtitle: "What You Want",
    primitives: [
      {
        name: "Intent",
        pillars: ["Language"],
        formationRate: "<1%",
        tamUnlocked: "$600B+",
        maturity: "Emerging",
        definition: "Explicit expression of a goal",
        legacyEquivalent:
          "Search queries, RFPs, want ads, classified listings",
        instantiations: [
          { name: "Index" },
          { name: "ERC-7683" },
          { name: "Anoma" },
          { name: "Essential" },
          { name: "SUAVE", approach: "Flashbots" },
        ],
        composesWith: [
          "Opportunity",
          "Appropriateness",
          "Memory",
          "Preference",
        ],
      },
      {
        name: "Opportunity",
        pillars: ["Language"],
        formationRate: "<1%",
        tamUnlocked: "$500B+",
        maturity: "Experimental",
        definition:
          "Matched mutual intents that conform to contextual integrity",
        legacyEquivalent:
          "Ads, job boards, matchmaking, marketplace listings",
        instantiations: [
          { name: "Index" },
          { name: "Braintrust" },
          { name: "XMTP" },
          { name: "Farcaster Frames" },
        ],
        composesWith: ["Intent", "Consent", "Conversation", "Offer / Bid"],
      },
      {
        name: "Offer / Bid",
        pillars: ["Money", "Language"],
        formationRate: "~3%",
        tamUnlocked: "$20B+",
        maturity: "Emerging",
        definition: "Priced commitment to fulfill an intent",
        legacyEquivalent:
          "Price quotes, proposals, auction bids, RFP responses",
        instantiations: [
          { name: "Seaport" },
          { name: "CoW Protocol" },
          { name: "Uniswap" },
          { name: "Request Network" },
        ],
        composesWith: [
          "Intent",
          "Opportunity",
          "Transaction",
          "Smart Contract",
        ],
      },
      {
        name: "Priority",
        pillars: ["Coordination"],
        formationRate: "<1%",
        tamUnlocked: "$10B+",
        maturity: "Theoretical",
        definition: "Ranked ordering of intents or commitments",
        legacyEquivalent:
          "Roadmaps, triage systems, backlogs, priority queues",
        instantiations: [
          { name: "Conviction Voting" },
          { name: "Coordinape" },
          { name: "Jokerace" },
        ],
        composesWith: ["Intent", "Decision", "Vote", "Commitment"],
      },
    ],
  },
  {
    layer: "Interaction",
    label: "L4 \u2014 Interaction",
    subtitle: "What Happens",
    primitives: [
      {
        name: "Conversation",
        pillars: ["Language", "Coordination"],
        formationRate: "~5%",
        tamUnlocked: "$50B+",
        maturity: "Emerging",
        definition: "Structured exchange between parties",
        legacyEquivalent: "Phone calls, emails, meetings, chat",
        instantiations: [
          { name: "XMTP" },
          { name: "Matrix/Element" },
          { name: "Waku" },
          { name: "Farcaster" },
          { name: "Push Protocol" },
        ],
        composesWith: ["Intent", "Consent", "Transaction", "Decision"],
      },
      {
        name: "Transaction",
        pillars: ["Money"],
        formationRate: "~2%",
        tamUnlocked: "$200B+",
        maturity: "Growing",
        definition: "Value transfer between parties",
        legacyEquivalent: "Wire transfers, card payments, invoices, checks",
        instantiations: [
          { name: "USDC/USDT" },
          { name: "Lightning Network" },
          { name: "Solana Pay" },
          { name: "Circle" },
          { name: "Stripe", approach: "crypto" },
        ],
        composesWith: [
          "Token",
          "Smart Contract",
          "Conversation",
          "Offer / Bid",
        ],
      },
      {
        name: "Decision",
        pillars: ["Language", "Coordination"],
        formationRate: "<1%",
        tamUnlocked: "$8B+",
        maturity: "Experimental",
        definition: "Recorded choice with rationale",
        legacyEquivalent:
          "Meeting minutes, approval workflows, board resolutions",
        instantiations: [
          { name: "Snapshot" },
          { name: "Tally" },
          { name: "Index" },
          { name: "Boardroom" },
        ],
        composesWith: ["Vote", "Proposal", "Commitment", "Memory"],
      },
      {
        name: "Commitment",
        pillars: ["Coordination"],
        formationRate: "~1%",
        tamUnlocked: "$50B+",
        maturity: "Experimental",
        definition: "Binding promise between parties",
        legacyEquivalent: "Contracts, handshakes, SLAs, MOUs",
        instantiations: [
          { name: "Smart contracts" },
          { name: "Allo Protocol" },
          { name: "Superfluid" },
          { name: "ERC-7683" },
        ],
        composesWith: [
          "Smart Contract",
          "Escrow",
          "Priority",
          "Decision",
          "Agreement",
        ],
      },
      {
        name: "Smart Contract",
        pillars: ["Money", "Coordination"],
        formationRate: "~2%",
        tamUnlocked: "$1T+",
        maturity: "Growing",
        definition: "Self-executing agreement",
        legacyEquivalent: "Legal contracts + lawyers + escrow agents",
        instantiations: [
          { name: "Ethereum" },
          { name: "Solana" },
          { name: "Arbitrum/Base" },
          { name: "CosmWasm" },
          { name: "Stylus" },
        ],
        composesWith: [
          "Transaction",
          "Commitment",
          "Escrow",
          "DeFi",
          "Token",
        ],
      },
      {
        name: "Agreement",
        pillars: ["Language", "Coordination"],
        formationRate: "<1%",
        tamUnlocked: "$50B+",
        maturity: "Emerging",
        definition:
          "Formalized binding arrangement between parties with verifiable execution",
        legacyEquivalent:
          "DocuSign, NDAs, service agreements, legal contracts, MOUs",
        instantiations: [
          { name: "Agreements Protocol" },
          { name: "EthSign" },
          { name: "Allo Protocol" },
        ],
        composesWith: [
          "Commitment",
          "Smart Contract",
          "Intent",
          "Consent",
          "Identity",
          "Credential / Claim",
          "Escrow",
        ],
      },
    ],
  },
  {
    layer: "Trust",
    label: "L5 \u2014 Trust",
    subtitle: "What You\u2019ve Earned",
    primitives: [
      {
        name: "Reputation",
        pillars: ["Language", "Coordination"],
        formationRate: "<1%",
        tamUnlocked: "$50B+",
        maturity: "Experimental",
        definition: "Aggregated trust signal",
        legacyEquivalent:
          "Credit scores, Yelp reviews, professional references",
        instantiations: [
          { name: "EAS" },
          { name: "Gitcoin Passport" },
          { name: "Index" },
          { name: "DegenScore" },
          { name: "Farcaster" },
        ],
        composesWith: [
          "Credential",
          "Attestation",
          "Endorsement",
          "Vouch",
          "Perception",
        ],
      },
      {
        name: "Endorsement",
        pillars: ["Language", "Coordination"],
        formationRate: "<1%",
        tamUnlocked: "$5B+",
        maturity: "Experimental",
        definition: "Explicit positive signal about another party",
        legacyEquivalent:
          "LinkedIn endorsements, testimonials, recommendations",
        instantiations: [
          { name: "Farcaster" },
          { name: "Lens" },
          { name: "EAS" },
          { name: "Index" },
          { name: "Coordinape" },
        ],
        composesWith: ["Reputation", "Credential", "Vouch", "Credibility"],
      },
      {
        name: "Vouch",
        pillars: ["Coordination"],
        formationRate: "<1%",
        tamUnlocked: "$10B+",
        maturity: "Experimental",
        definition: "Stake-backed trust delegation",
        legacyEquivalent: "Personal references, guarantors, co-signers",
        instantiations: [
          { name: "Union Protocol" },
          { name: "Ethereum", approach: "staking" },
          { name: "Eigenlayer" },
          { name: "WorldID" },
        ],
        composesWith: ["Reputation", "Endorsement", "Commitment", "Risk"],
      },
      {
        name: "Perception",
        pillars: ["Language"],
        formationRate: "<1%",
        tamUnlocked: "$20B+",
        maturity: "Theoretical",
        definition: "Agent-interpreted social behavior",
        legacyEquivalent:
          "Gossip, social judgment, word of mouth, gut feeling",
        instantiations: [
          { name: "Index", approach: "agent perception" },
          { name: "Neynar" },
          { name: "Kaito" },
        ],
        composesWith: [
          "Reputation",
          "Appropriateness",
          "Memory",
          "Endorsement",
        ],
      },
      {
        name: "Credibility",
        pillars: ["Language", "Coordination"],
        formationRate: "<1%",
        tamUnlocked: "$15B+",
        maturity: "Theoretical",
        definition: "Demonstrated reliability over time",
        legacyEquivalent:
          "Track record, brand trust, certifications, tenure",
        instantiations: [
          { name: "On-chain history" },
          { name: "Gitcoin Passport" },
          { name: "DegenScore" },
          { name: "EAS" },
        ],
        composesWith: ["Reputation", "Attestation", "Commitment", "Vouch"],
      },
    ],
  },
  {
    layer: "Value",
    label: "L6 \u2014 Value",
    subtitle: "What Flows",
    primitives: [
      {
        name: "Token",
        pillars: ["Money"],
        formationRate: "~5%",
        tamUnlocked: "$400T+",
        maturity: "Growing",
        definition: "Programmable unit of value",
        legacyEquivalent:
          "Currency, loyalty points, shares, bonds, gift cards",
        instantiations: [
          { name: "ETH" },
          { name: "USDC/USDT" },
          { name: "Ondo" },
          { name: "BlackRock BUIDL" },
          { name: "Uniswap" },
        ],
        composesWith: [
          "Transaction",
          "Stream",
          "DeFi",
          "Smart Contract",
          "Escrow",
        ],
      },
      {
        name: "Stream",
        pillars: ["Money", "Coordination"],
        formationRate: "<1%",
        tamUnlocked: "$30B+",
        maturity: "Emerging",
        definition: "Continuous value flow over time",
        legacyEquivalent:
          "Salaries, subscriptions, recurring payments, royalties",
        instantiations: [
          { name: "Superfluid" },
          { name: "Sablier" },
          { name: "Drips" },
          { name: "LlamaPay" },
          { name: "Splits" },
        ],
        composesWith: ["Token", "Commitment", "Smart Contract", "Task"],
      },
      {
        name: "Escrow",
        pillars: ["Money", "Coordination"],
        formationRate: "~2%",
        tamUnlocked: "$15B+",
        maturity: "Emerging",
        definition: "Conditionally held value",
        legacyEquivalent: "Escrow agents, holding accounts, trust accounts",
        instantiations: [
          { name: "Smart contract escrow" },
          { name: "Kleros" },
          { name: "Allo Protocol" },
          { name: "Safe" },
        ],
        composesWith: [
          "Smart Contract",
          "Commitment",
          "Arbitration",
          "Transaction",
          "Agreement",
        ],
      },
      {
        name: "DeFi (Liquidity)",
        pillars: ["Money", "Coordination"],
        formationRate: "~1%",
        tamUnlocked: "$100B+",
        maturity: "Growing",
        definition: "Automated market infrastructure",
        legacyEquivalent: "Banks, stock exchanges, market makers, brokers",
        instantiations: [
          { name: "Uniswap" },
          { name: "Aave" },
          { name: "MakerDAO" },
          { name: "Curve" },
          { name: "Compound" },
        ],
        composesWith: [
          "Token",
          "Smart Contract",
          "Transaction",
          "Risk",
          "Oracle",
        ],
      },
      {
        name: "Risk",
        pillars: ["Money", "Language"],
        formationRate: "<1%",
        tamUnlocked: "$100B+",
        maturity: "Experimental",
        definition: "Quantified uncertainty as a tradeable primitive",
        legacyEquivalent:
          "Insurance, credit ratings, hedging instruments",
        instantiations: [
          { name: "Nexus Mutual" },
          { name: "Etherisc" },
          { name: "Polymarket" },
          { name: "Opyn" },
        ],
        composesWith: [
          "DeFi (Liquidity)",
          "Prediction Market",
          "Vouch",
          "Token",
          "Credibility",
        ],
      },
    ],
  },
  {
    layer: "Coordination",
    label: "L7 \u2014 Coordination",
    subtitle: "How You Organize",
    primitives: [
      {
        name: "Vote",
        pillars: ["Coordination"],
        formationRate: "~2%",
        tamUnlocked: "$5B+",
        maturity: "Emerging",
        definition: "Weighted preference expression",
        legacyEquivalent:
          "Ballots, shareholder proxy votes, board votes, polls",
        instantiations: [
          { name: "Snapshot" },
          { name: "Tally" },
          { name: "Aragon" },
          { name: "Governor", approach: "OpenZeppelin" },
          { name: "Jokerace" },
        ],
        composesWith: ["Proposal", "Decision", "Delegation", "Token"],
      },
      {
        name: "Proposal",
        pillars: ["Language", "Coordination"],
        formationRate: "<1%",
        tamUnlocked: "$3B+",
        maturity: "Emerging",
        definition: "Formal request for collective action",
        legacyEquivalent: "Bills, motions, RFCs, budget requests",
        instantiations: [
          { name: "Snapshot" },
          { name: "Tally" },
          { name: "Nouns" },
          { name: "Compound Governor" },
          { name: "Moloch DAO" },
        ],
        composesWith: ["Vote", "Decision", "Commitment", "Treasury"],
      },
      {
        name: "Delegation",
        pillars: ["Coordination"],
        formationRate: "<1%",
        tamUnlocked: "$5B+",
        maturity: "Emerging",
        definition: "Transferring authority to act on behalf",
        legacyEquivalent:
          "Power of attorney, representative democracy, proxies",
        instantiations: [
          { name: "ENS delegation" },
          { name: "Compound delegation" },
          { name: "Agora" },
          { name: "Karma" },
          { name: "AI agent delegation" },
        ],
        composesWith: ["Vote", "Agent", "Identity", "Commitment"],
      },
      {
        name: "Arbitration",
        pillars: ["Coordination"],
        formationRate: "<1%",
        tamUnlocked: "$20B+",
        maturity: "Experimental",
        definition: "Dispute resolution mechanism",
        legacyEquivalent:
          "Courts, mediators, customer service, chargeback systems",
        instantiations: [
          { name: "Kleros" },
          { name: "Aragon Court" },
          { name: "UMA" },
          { name: "Reality.eth" },
        ],
        composesWith: [
          "Smart Contract",
          "Escrow",
          "Decision",
          "Commitment",
          "Agreement",
        ],
      },
      {
        name: "Prediction Market",
        pillars: ["Money", "Language"],
        formationRate: "~2%",
        tamUnlocked: "$30B+",
        maturity: "Growing",
        definition: "Collective intelligence through priced beliefs",
        legacyEquivalent:
          "Polls, analyst forecasts, futures markets, expert panels",
        instantiations: [
          { name: "Polymarket" },
          { name: "Kalshi" },
          { name: "Augur" },
          { name: "Metaculus" },
          { name: "Manifold Markets" },
        ],
        composesWith: ["Risk", "Token", "Knowledge", "Decision", "Oracle"],
      },
    ],
  },
  {
    layer: "Agents",
    label: "L8 \u2014 Agents",
    subtitle: "Who Acts For You",
    primitives: [
      {
        name: "Agent",
        pillars: ["Language"],
        formationRate: "<1%",
        tamUnlocked: "$500B+",
        maturity: "Emerging",
        definition: "Autonomous actor on behalf of a human",
        legacyEquivalent: "Employees, brokers, assistants, contractors",
        instantiations: [
          { name: "Index" },
          { name: "Autonolas" },
          { name: "Fetch.ai" },
          { name: "Virtuals Protocol" },
          { name: "Eliza", approach: "ai16z" },
        ],
        composesWith: ["Intent", "Memory", "Delegation", "Task", "Identity"],
      },
      {
        name: "Task",
        pillars: ["Language", "Money"],
        formationRate: "<1%",
        tamUnlocked: "$100B+",
        maturity: "Experimental",
        definition: "Delegated unit of work with value attached",
        legacyEquivalent:
          "Job postings, work orders, gig assignments, tickets",
        instantiations: [
          { name: "Braintrust" },
          { name: "Keep3r Network" },
          { name: "Gelato" },
          { name: "Human Protocol" },
        ],
        composesWith: ["Agent", "Commitment", "Stream", "Token", "Workflow"],
      },
      {
        name: "Oracle",
        pillars: ["Language", "Coordination"],
        formationRate: "~5%",
        tamUnlocked: "$10B+",
        maturity: "Growing",
        definition: "Verified external data source",
        legacyEquivalent:
          "Data providers, auditors, fact-checkers, news agencies",
        instantiations: [
          { name: "Chainlink" },
          { name: "Pyth" },
          { name: "UMA" },
          { name: "API3" },
          { name: "Pragma" },
        ],
        composesWith: [
          "Knowledge",
          "DeFi (Liquidity)",
          "Prediction Market",
          "Smart Contract",
          "Decision",
        ],
      },
      {
        name: "Workflow",
        pillars: ["Language", "Coordination"],
        formationRate: "~1%",
        tamUnlocked: "$15B+",
        maturity: "Experimental",
        definition: "Composed sequence of tasks and decisions",
        legacyEquivalent:
          "Business processes, assembly lines, SOPs, IFTTT/Zapier",
        instantiations: [
          { name: "Autonolas" },
          { name: "LangChain/LangGraph" },
          { name: "Safe" },
          { name: "Geist" },
        ],
        composesWith: [
          "Agent",
          "Task",
          "Decision",
          "Smart Contract",
          "Oracle",
        ],
      },
    ],
  },
];

const SUMMARY = {
  totalPrimitives: 37,
  totalLayers: 8,
  avgFormationRate: "~1.5%",
  totalTAM: "~$2.6T+",
};
